### ISSUE TITLE
Clarification needed on i3 in README

### ISSUE THREAD

**Issue by jwatt** [lawleagle/oled-linux#3]
The installation section says "loads oled-linux and i3", but the dependencies section makes no mention of i3 as a dependency. Is there a dependency? If not, why include a tiling window manager in the setup instructions?

**Comment by lawleagle** [comment]
And in the whole context it says "This is an example of an .xinitrc that loads oled-linux and i3". oled-linux and i3 are 2 different things, i3 is not a dependency, has nothing to do with the project, it's just an example. Instead of i3, you can load anything.

**Comment by jwatt** [comment]
Thanks for the reply. I saw that, but it seemed like i3 was maybe a necessary part of the example, since otherwise it seemed like a bit of a random thing to throw in there. But maybe there's a reason that I'm not getting, such as maybe the scripts need to run before your window manager and you're trying to suggest that? Either way, for uninitiated users like myself it might be less confusing to tweak the text. Maybe the following (edits in bold):

"This is an example of an .xinitrc that loads oled-linux **for a user that is using** i3. **Note that the oled-linux scripts must be invoked before your window manager is started**."

Anyway, just my "new user eyes" 2c. Either way, thank you for making oled-linux and making it available.

**Comment by lawleagle** [comment]
This was really unexpected, I didn't want to include both of them because I didn't want to make the script longer for no reason, "the script must be invoked before your window manager" seemed too obvious to me, but today I realized it's not when someone had that problem. Thanks. Have a good one.

**Comment by jwatt** [comment]
Thank you! Hopefully that helps someone else with an OLED laptop taking their first steps in Linux in future. :-)
