### ISSUE TITLE
How to get this to work in KDE

### ISSUE THREAD

**Issue by TheSycamore** [lawleagle/oled-linux#6]
Firstly thank you so much for making this software.
I am having issues getting it to work on:

- Dell XPS 7590 (OLED screen)
- Kubuntu 20.04

I am confused about which file to add the following lines from the documentation.
I am using KDE as the Desktop Environment/Window Manager and not i3. I don't know which file to add this to that will 

> be invoked before your window manager is started.

```
<path-to>/oled-linux/get-current-location.sh &  # optional, for night-light-geolocation
<paht-to>/oled-linux/watch-location.sh &        # optional, for night-light-geolocation
<path-to>/oled-linux/run-set-day-night.sh &     # optional, for night-light
<path-to>/oled-linux/oled-linux.sh &
exec i3
```

I have attempted creating a file called:
`~/.xinitrc`
I put the above lines in (with correct paths) and rebooted but it doesn't work.

Any help in troubleshooting this would be super helpful.
Thank you.

**Comment by TheSycamore** [comment]
I have ended up using this solution for the Dell XPS 7590 for anyone who faced the same issues as me:
https://github.com/MuDiAhmed/Ubuntu-Dell-XPS-15-2019

**Comment by TheSycamore** [comment]
I have ended up using this solution for the Dell XPS 7590 for anyone who faced the same issues as me:
https://github.com/MuDiAhmed/Ubuntu-Dell-XPS-15-2019

**Comment by lawleagle** [comment]
To make this script work on KDE, .xprofile should work, or you can start the scripts with autostart.

Also, I checked the brightness scripts in the project you linked, and there are a few things I think you should check:

1. icc_brightness should get the job done, but make sure it's smooth. We wouldn't want a new, awesome, shiny DELL XPS without smooth brightness changes :)
2. If you care, make sure it works with a night light filter (redshift). I think it might not.
3. Make sure it works if you change the brightness file manually. KDE sometimes changes that file for some nice desktop effects, and we want that to work. (again, icc_brightness should do this if set up correctly)

**Comment by TheSycamore** [comment]
Thank you so lawleagle much for getting back with your helpful reply!
